### ISSUE TITLE
vike-react-query withFallback error prop does not include error properties

### ISSUE THREAD

**Issue by Alduino** [vikejs/vike-react#101]
Using vike-react-query (v0.0.4), I've noticed that no errors caught by `withFallback`'s error boundary seem to have any of their standard properties, other than `message`.

For example:
```jsx
withFallback(
    () => {
        useSuspenseQuery({
            queryKey: ["test"],
            queryFn() {
                throw new Error("Test error!", {
                    cause: new Error("Another one!")
                });
            }
        });
        return null;
    },
    {
        Error({error}) {
            console.log("ERROR LOG:", error);
            return null;
        }
    }
);
```

I would have expected this code to log an object with `name`, `message`, `cause`, and `stack` properties, but it only has `message`.

As far as I can tell, the cause of this is because `Error` keys are not enumerable, so they are ignored in the `Object.assign` call that creates the error prop. Trying this directly in the console does the same thing - `Object.assign({message: "test"}, new Error("Test!"))` returns `{message: "test"}`.

**Comment by nitedani** [comment]
Thank you for reporting the issue!

Fix pre-relased as `0.0.4-commit-7a99687`

**Comment by Alduino** [comment]
Thank you for fixing that so quick! Though, it seems the prerelease hasn't gone out to npm?

**Comment by nitedani** [comment]
My mistake, published it now.
