### ISSUE TITLE
`clientOnly()` instead of `<ClientOnly>`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-react#102]
See `vike-solid`'s [`clientOnly()`](https://vike.dev/clientOnly#solid).

A `clientOnly()` helper is a much nicer DX than a `<ClientOnly>` wrapper.

Contribution welcome.

See also:
 - https://docs.solidjs.com/solid-start/reference/client/client-only

**Comment by nitedani** [comment]
Completed in https://github.com/vikejs/vike-react/pull/127
