### ISSUE TITLE
routeParams did not pass on the client-side by default

### ISSUE THREAD

**Issue by zhy0216** [vikejs/vike-react#104]
on doc it mentioned it should: https://vike.dev/passToClient#default

**Comment by brillout** [comment]
Indeed it should.

I cannot reproduce. Can you publish a minimal reproduction? I'll re-open then.

**Comment by zhy0216** [comment]
Hi @brillout, if you can go to minimal example in this repo, and use `pageContext.routeParams` in the +Page. Then open dev tool in browser then you can see the following errors. 
<img width="535" alt="Screenshot 2024-04-16 at 16 14 55" src="https://github.com/vikejs/vike-react/assets/903908/86199026-f509-4375-b359-96f9ddd00c52">

**Comment by brillout** [comment]
It's because the page doesn't have any route parameters. That said, the error is misleading and should be improved. Labeling this as bug.

**Comment by brillout** [comment]
`pageContext.routeParams` is now always passed regardless of whether the page has a route parameter.
