### ISSUE TITLE
Vike error on 

### ISSUE THREAD

**Issue by KarthikrajS** [vikejs/vike-react#114]
![Screenshot 2024-05-16 at 5 38 58 PM](https://github.com/vikejs/vike-react/assets/8804682/7e45f787-52b9-4636-a647-95a277bc9c04)
[vike-bloomify-2.zip](https://github.com/vikejs/vike-react/files/15334897/vike-bloomify-2.zip)

**Comment by brillout** [comment]
Can you publish the reproduction as GitHub repo?

**Comment by brillout** [comment]
I'll re-open once I can get my hands on reproduction published to GitHub.
