### ISSUE TITLE
vike-react-query throws error in `onRenderHtml`

### ISSUE THREAD

**Issue by jordyalcides** [vikejs/vike-react#129]
#### Describe the bug
Starting a new project using vike-react-query throws an error after the first page request

#### To Reproduce
Steps to reproduce the behavior, run the following commands in order:

`pnpm create @batijs/app --react --tailwindcss --hono --cloudflare --prettier`

than `pnpm add @tanstack/react-query vike-react-query`

than change the `pages/+config.ts` to include vike-react-query plugin on extends prop

```
export default {
	Head,
	title: 'My Vike App',
	extends: [vikeReact, vikeReactQuery],
	passToClient: ['routeParams'],
} satisfies Config

```
setup everything as the [docs](https://github.com/vikejs/vike-react/tree/main/packages/vike-react-query) mention 

#### Expected behavior
Run dev mode without any errors

Screenshots
![Screenshot 2024-07-09 at 17 52 40](https://github.com/vikejs/vike-react/assets/9451041/485e0825-460c-46e3-be5f-aa46e6dfd5d0)

Additional context
Using macOS Ventura 13.6.6 and the following related libs:

    "react": "^18.3.1",
    "@hono/node-server": "^1.12.0",
    "hono": "^4.4.11",
    "@vitejs/plugin-react": "^4.3.1",
    "vike": "^0.4.178",
    "vike-cloudflare": "^0.0.4",
    "vike-react": "^0.4.16",
    "vike-react-query": "^0.1.0",
    "vite": "^5.3.3",

**Comment by brillout** [comment]
Can you publish a reproduction?

**Comment by brillout** [comment]
How did you resolve your `#1729` issue btw.?

**Comment by jordyalcides** [comment]
> Can you publish a reproduction?

I could reproduce it on stackblitz using this run command:

`pnpm create @batijs/app --react --tailwindcss --hono --cloudflare --prettier`

than `pnpm add @tanstack/react-query vike-react-query`

than change the `pages/+config.ts` to include vike-react-query plugin on extends prop

```
export default {
	Head,
	title: 'My Vike App',
	extends: [vikeReact, vikeReactQuery],
	passToClient: ['routeParams'],
} satisfies Config

```

**Comment by brillout** [comment]
Make sure to set `stream` to `web`.

Closing in favor of https://github.com/batijs/bati/discussions/303.
