### ISSUE TITLE
Hono compress plugin 

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike-react#143]
I found issue while using hono and compress plugin. 

![image](https://github.com/user-attachments/assets/ae969cdd-c4f5-44bc-8664-b2957f3c1386)

How to reproduce
- Create vike hono app using batijs
- Add script 
```
import { compress } from "hono/compress";
const app = new Hono();
app.use(compress());
```
- Build and run preview

But while I try to reproduce using https://github.com/phonzammi/vike-hono-example 's template.. the template using compress plugin and the app running properly

**Comment by brillout** [comment]
https://github.com/vikejs/vike-node/issues/7#issuecomment-2307061490

**Comment by phonzammi** [comment]
> * Add script

Why do you need to add that code? Bati's template already includes it. See:

https://github.com/vikejs/bati/blob/978301cc88be68308b88fc564b8d5b6b03a02a95/boilerplates/hono/files/hono-entry.node.ts#L12
