### ISSUE TITLE
Destructuring usePageContext in useData will cause an error in test runners

### ISSUE THREAD

**Issue by shahyar** [vikejs/vike-react#147]
https://github.com/vikejs/vike-react/blob/9232140f5888fe955bd7643b113a3c8b4634c2b9/packages/vike-react/src/hooks/useData.tsx#L6

Just realized that if I have a test like 
```ts
import { render } from '@testing-library/react';

import Page from './+Page'; // export default () => useData();

describe('<Page />', () => {
  it('should render Page', async () => {
    const { container } = render(<Page />);
    // ...
  });
});
```

This will error out with `TypeError: Cannot destructure property 'data' of 'usePageContext(...)' as it is undefined.` Should we change that to `return (usePageContext() as any)?.data` instead? Or is there a better way to adapt my tests to account for the necessary contexts vike-react needs?

**Comment by brillout** [comment]
Fix pre-released as `vike-react@0.5.5-commit-68b6dc0`. (As for E2E frontend tests I generally recommend using playwright.)
