### ISSUE TITLE
Example that includes a server to use along side vike-react

### ISSUE THREAD

**Issue by drew-dulgar** [vikejs/vike-react#149]
Hi - Is there an example out there that uses an express server to pipe the response from vike-react's onRenderHtml? 

I am having a heck of a time. I tried generating an example from Bati - however, that seems to generate yet another dependency on another library `"@universal-middleware/express` to create the response handler. As it stands, I have a little bit put together. Everything runs completely fine using `vite dev`, however, whenever i try to run it through my own little express server, it fails with the following error, as it seems react-vike will *only* stream the value:

`Error: [vike][Wrong Usage] pageContext.httpResponse.body can't be used because the onRenderHtml() hook defined by vike-react/__internal/integration/onRenderHtml provides a Node.js Stream Pipe. Use pageContext.httpResponse.pipe() instead. See https://vike.dev/streaming for more information.`

I understand that i need to pipe a response in the response handler... but then i just get errors about how vike-react is using a nodeJS stream, and its being provided a web stream. 

I just need a small push in the right direction, as i am a bit over my head at the moment.... 

I see this comment: ` // For HTTP streams use pageContext.httpResponse.pipe() instead, see https://vike.dev/streaming`
However, i just seem to make things even worse trying to follow those docs .

Am I just completely whiffing an understanding here? I'm not sure... 

./server/index.js
```js
// This file isn't processed by Vite, see https://github.com/vikejs/vike/issues/562
// Consequently:
//  - When changing this file, you needed to manually restart your server for your changes to take effect.
//  - To use your environment variables defined in your .env files, you need to install dotenv, see https://vike.dev/env
//  - To use your path aliases defined in your vite.config.js, you need to tell Node.js about them, see https://vike.dev/path-aliases
import express from 'express';
import compression from 'compression';
import { renderPage } from 'vike/server';
import { root } from './root.js';

const isProduction = process.env.NODE_ENV === 'production';
const port = process.env.PORT || 3050;

const startServer = async () => {
  const app = express();

  app.use(compression());

  // Vite integration
  if (isProduction) {
    // In production, we need to serve our static assets ourselves.
    // (In dev, Vite's middleware serves our static assets.)
    const sirv = (await import('sirv')).default;
    app.use(sirv(`${root}/dist/client`));
  } else {
    // We instantiate Vite's development server and integrate its middleware to our server.
    // ⚠️ We instantiate it only in development. (It isn't needed in production and it
    // would unnecessarily bloat our production server.)
    const vite = await import('vite');
    const viteDevMiddleware = (
      await vite.createServer({
        root,
        server: { middlewareMode: true }
      })
    ).middlewares;
    app.use(viteDevMiddleware);
  }


  app.get('*', async (req, res) => {
    const pageContextInit = {
      urlOriginal: req.originalUrl,
      headersOriginal: req.headers
    };

    const pageContext = await renderPage(pageContextInit);

    if (pageContext.errorWhileRendering) {
      // Install error tracking here, see https://vike.dev/error-tracking
    }

    const { httpResponse } = pageContext;

    if (res.writeEarlyHints) res.writeEarlyHints({ link: httpResponse.earlyHints.map((e) => e.earlyHintLink) });
    httpResponse.headers.forEach(([name, value]) => res.setHeader(name, value));
    res.status(httpResponse.statusCode);
    // For HTTP streams use pageContext.httpResponse.pipe() instead, see https://vike.dev/streaming
    res.send(httpResponse.body)
  });

  app.listen(port);
  console.log(`Server running at http://localhost:${port}`);
}

startServer();
```

**Comment by fortezhuo** [comment]
I suggest you to take a look of [vike-node](https://github.com/vikejs/vike-node)
I had refactored my code using vike-node, and happy with it.

**Comment by drew-dulgar** [comment]
Wow! That seemed to have helped out a TON!! THANK YOU! Server code  is much cleaner and it does appear to be rendering everything as expected!!

**Comment by brillout** [comment]
Thank you for reaching out. We should improve the docs around manual server integration. In the meantime the goal is to have `vike-node` handle all the heavy lifting. Closing as OP seem to have resolved his issue. @fortezhuo Thank you for chiming in.
