### ISSUE TITLE
grabbing cookies on server for fetch requests outside of UI components.

### ISSUE THREAD

**Issue by drew-dulgar** [vikejs/vike-react#150]
Hi. Really enjoying these products. I am learning a lot (while making a lot of mistakes along the way hah. I just wanted to verify if I am doing something wrong here, or if it's an anti pattern. It works, but I fear I don't know enough to understand the potential ramifications as of this point. 

So... I have things abstracted to various layers. A service layer, a query layer, then of course the component layer. 

My services need access to a cookie that is used on both the client and server side to make authenticated requests, and I'm curious if this can be done better? Or if I am introducing possible issues.

Basically, the structure looks similar to this... Mostly done through common services but this will be shorted for example purposes.

services/account.js
```js
Class AccountService {
  credentials() {
    If (import.meta.env.SSR)
      const pageContext= use pageContext();

       return {
         'Cookie': pageContext.headers.cookie
       };
    }
    return {};
  }

  get() {
     return fetch('/account', {
       headers: {
         ...this.credentials()
       },
       credentials: 'include'
  }
}

export default new AccoutService();
```

queries/account.js
```js
const useAccount = (options = {}) = useSuspenseQuery({
  ...options,
  queryKey: ['QUERY_ACCOUNT'],
  queryFn: AccountService.get
});
```

component.jsx
```js
const Component = () => {
   const account = useAccount();

   return account.data.username;
};
```

This setup allows me to use the same query in multiple places, on the server or client, and get the full benefit of server rendering and hydration to the client. Along with auth across the board.

Now the question... Is this bad? If this isn't how I should be forwarding cookies - are there suggestions?

**Comment by brillout** [comment]
From Vike's perspective it's fine: you're essentially calling `usePageContext()` inside a component to access the headers. That said, the code you're sharing seems a little bit convoluted at first sight, but that's more of a React questions than a Vike one. In general, we're trying to focus discussions here to be about Vike.

**Comment by drew-dulgar** [comment]
Thanks @brillout . I just needed some reassurance that the conditional call to usePageContext wasn't causing some unforseen issues. 

It does throw an error without being wrapped in the SSR check, (client side only). I don't quite understand why - as usePageContext is both client and server - and always called at its core from within the react component tree. 

Weird behavior, but I'll move forward as is for now.

**Comment by brillout** [comment]
> conditional call to usePageContext wasn't causing some unforseen issues

Not from vike(-react) itself, but React will complain as `usePageContext()` is a React hook.

> It does throw an error without being wrapped in the SSR check, (client side only). I don't quite understand why - as usePageContext is both client and server - and always called at its core from within the react component tree.

This seems to be more of a React question, but feel free to elaborate if you have evidence/confidence it's Vike related.
