### ISSUE TITLE
Expose `pageContext` to `Head`

### ISSUE THREAD

**Issue by eternaleye** [vikejs/vike-react#24]
A site I'm working on needs to have access to `pageContext` (particularly `routeParams`) in `Head`, in order to emit OpenGraph metadata that depends upon it. However, the current `onRenderHtml` does not wrap the `Head` in `PageContextProvider`.

**Comment by brillout** [comment]
It actually does wrap it:

```tsx
  const head = (
    <React.StrictMode>
      <PageContextProvider pageContext={pageContext}>
        <Head />
      </PageContextProvider>
    </React.StrictMode>
  )
```

See `vike-react/renderer/onRenderHtml.tsx`.
