### ISSUE TITLE
React Developer Tools doesn't work on first render

### ISSUE THREAD

**Issue by ruigouveiamaciel** [vikejs/vike-react#25]
# Issue description

Whenever you try to render a page for the first time (in development mode), the React Developer Tools will timeout and error.

![Screenshot from 2023-10-03 11-16-24](https://github.com/vikejs/vike-react/assets/17518628/e87a6f02-750c-49a7-922c-ae35243e6471)

# Other behaviors

1. Some components, for some odd reason, never timeout and actually work, such as the `Logo` component. However, in the [/examples/ssr-spa](https://github.com/vikejs/vike-react/tree/05da94135b8b75b95d1decbae29abe4fcea040ce/examples/ssr-spa), the `Link` component seems to always timeout of the first render.

2. Sometimes React Developer Tools will straight up just refuse to even load the DOM

    ![image](https://github.com/vikejs/vike-react/assets/17518628/abf7074d-58e5-4423-b990-383fe1762b0b)

3. Because this example is using client routing, whenever you switch to another page and then page to the same page React Developer Tools will not timeout anymore and work as expected.
    
    [Screencast from 03-10-2023 11:38:08.webm](https://github.com/vikejs/vike-react/assets/17518628/c086f268-107a-489f-8119-ec5126275270)
    
# Fix suggestion

I believe the root of the issue is because the first render is handled by onRenderHtml, which handles the creation of the page. The client, on the first render, only hydrates the page and therefore is lacking some information required by React Developer Tools.

After the first render, client routing takes control and therefore there's no longer the issue of the client missing any information required by the React Developer Tools.

I found out that by adding `'$$typeof'` to [passToClient](https://github.com/vikejs/vike-react/blob/05da94135b8b75b95d1decbae29abe4fcea040ce/vike-react/renderer/%2Bconfig.ts#L28) fixes this issue.

```ts
// /vike-react/renderer/+config.ts

export default {
  // ...
  passToClient: ['pageProps', 'title', '$$typeof']
  // ...
} satisfies Config
```

I was going to make a pull request for this, however this seems like a very small change and I don't know if it's the best approach to fixing it.

It would also be useful to extend the documentation with this information for people that are trying to build their own renderers/frameworks.

If you're happy with my proposed fix, I could go ahead and create a pull request for both the issue and the documentation. However I don't know what's the most appropriate place to document this.

**Comment by AurelienLourot** [comment]
Hey @ruigouveiamaciel, thank you so much for digging into it. Adding `$$typeof` with a comment sounds good to me. Do you have a link to React's documentation or source-code or else describing this?

The documentation of [Vike's V1 design](https://vite-plugin-ssr.com/migration/v1-design) is in construction, as well as the documentation of `vike-{react,vue,solid}`. The idea is that we want to document things which are common to all three `vike-*` at vike.dev, e.g. https://vike.dev/vike-packages and https://vike.dev/usePageContext.

And we want the documentation specific to vike-react to live in this repo. Feel free to give a shot at writing some documentation and we'll maybe just move it at some point. Thanks!

**Comment by ruigouveiamaciel** [comment]
Hey @AurelienLourot, `$$typeof` is a property that exists in all react components and it's used for many things, including determining what component the element is. 

About 4 years ago I recall having a similar issue with the React Developer Tools and it was because the framework I was using at the time was not preserving `$$typeof` for some reason. I don't recall what framework I was using nor how I found the fix for it.

I also noticed that the issue mostly only happens to the `<Page />` component and its children. React Developer Tools seems to always work with the parents of `<Page />` on my company's websites so I just had the idea of adding `$$typeof` to `passToClient` and it worked!

If you want to read more about `$$typeof` I can link you [the original pull request](https://github.com/facebook/react/pull/4832) for it.

**Comment by brillout** [comment]
@AurelienLourot I didn't read the whole thread, is there something actionable or can we close this?

**Comment by AurelienLourot** [comment]
@brillout we can just add `'$$typeof'` to `passToClient` in order to support the React Developer Tools. What do you think?

**Comment by brillout** [comment]
Hm, that's surprising: seems like React (or more likely its dev tool) is touching the `pageContext` object.

> 1. Some components, for some odd reason, never timeout and actually work, such as the `Logo` component. However, in the [/examples/ssr-spa](https://github.com/vikejs/vike-react/tree/05da94135b8b75b95d1decbae29abe4fcea040ce/examples/ssr-spa), the `Link` component seems to always timeout of the first render.

Makes me think that `$$typeof` is being added when `vike-react` adds `pageContext` to the React context for `usePageContext()`. (`<Link>` calls `usePageContext()`.)

I guess we can add it to `passToClient` if the value of `$$typeof` is small.

How about this: we add it to `passToClient` and add an `assert(!pageContext.$$typeof || typeof pageContext.$$typeof ==='string' &&  pageContext.$$typeof.length < 100)`? (Assuming it's a string.)

**Comment by AurelienLourot** [comment]
> `pageContext.$$typeof.length < 100`

Does this matter? Users who haven't installed the React Developer Tools won't be affected anyways and for the users having it installed, I guess it's fine if that means more data usage?

**Comment by brillout** [comment]
Are we sure it's only set for users who installed the dev tool browser extension? How about users who installed it but don't open the browser dev tool?

**Comment by ruigouveiamaciel** [comment]
I think $$typeof is part of the React documentation for the component class. Also the $$type is only needed during development, they could be a check to disable it after `vite build`

**Comment by ruigouveiamaciel** [comment]
I found this https://medium.com/@fengyu214/learning-react-source-code-ecfee15f875f

**Comment by ruigouveiamaciel** [comment]
> In case I didn't ask before: would your company be up for [sponsoring](https://github.com/vikejs/vike/issues/1350)?

Sadly I had to move away from my company because the CEO became a hype man/finance bro and ruined everything. Classic startup moment. They also trashed all of the Vite code I had written just because it was me that had written it, so they don't even use Vite anymore.

On my new job we're not using Vite so no luck there either.

**Comment by brillout** [comment]
I see. Thanks for the conversation.
