### ISSUE TITLE
`useId()` unusable with SSR

### ISSUE THREAD

**Issue by lourot** [vikejs/vike-react#36]
Moved from https://github.com/vikejs/vike/discussions/1291

`useId()` is supposed to generate deterministic unique IDs. Rendering the app first on the server and then on the client should lead to the same unique ID.

However in `vike-react`, because we feed react with different apps on server (including `<head>`) and on client (without `<head>`), we end up with different IDs, and so with hydration mismatches.

See [steps to reproduce](https://github.com/vikejs/vike/discussions/1291#discussion-5892063).

FYI @AndrejNemec

**Comment by brillout** [comment]
Makes sense, I think it's a regression that got introduced by https://github.com/vikejs/vike-react/pull/33.

**Comment by brillout** [comment]
@AndrejNemec PR welcome in case that's something you'd be interested in. The change is quite easy. Let us know if you're busy; we'll quickly fix it ourselves then.

**Comment by AndrejNemec** [comment]
Thank you for considering me for the PR contribution. I'm currently involved in a project named "vite-painless-react", which brings several key enhancements to the table:

    i18n Support: Integrated with the i18next package for comprehensive internationalization.
    Dark/Light Theme Support: Facilitates an easy switch between dark and light themes, fully compatible with both SSR and client-side environments.
    Enhanced HTML Head Management: Offers improved handling and functionality of the HTML head section.

You can explore the project here: [vite-painless-react](https://github.com/AndrejNemec/vike-painless-react)
For a practical implementation example, check out: [vite-painless-react example](https://github.com/AndrejNemec/vike-painless-react/tree/master/examples)

While I'm currently focused on developing this package, I see potential synergies with Vike. If integrating these features aligns with your vision, my package could serve as a useful reference or even as a direct addition to Vike. I'm open to discussions about possibly making this an official part of the Vike portfolio. Looking forward to hearing your thoughts! 😄🌟

**Comment by brillout** [comment]
@phonzammi Yes, that’s exactly the issue

**Comment by phonzammi** [comment]
@brillout 
Great, I've make a PR, 
Please review it, I have a question in the code comment

**Comment by AurelienLourot** [comment]
> I'm currently involved in a project named "vike-painless-react", which brings several key enhancements to the table:

@AndrejNemec It sounds like some of these enhancement should be made to vike-react (whose goal is also to be painless) and to the equivalent vike-vue and vike-solid packages. PRs welcome

**Comment by AurelienLourot** [comment]
Fixed in v0.3.5

**Comment by brillout** [comment]
> create an npm organization `@vike-react`,

That's a great idea. I just created four npm orgs: `@vike-{react,vue,solid,svelte}`.

> If you like this vision, we can jointly design it into the `vike-react` package, potentially replacing the `vike-painless-react` package.

Yes 👍

> regarding head management. How do you plan to implement it?

One major issue with title/description defined by components is that it contradicts streaming: when the HTML stream starts then it's too late for setting title/description (because the `<head>` content is already sent).

That's why I'm relunctant to allow users to let components define `<head>` values.

I'm thinking `+title.js` and `+description.js` is more future-proof.

As much as I'd love to have title/description defined by components, I don't think it's possible because of how browsers work.

**Comment by brillout** [comment]
Actually, I'm wrong: a workaround would be to push this after the stream ends:

```js
<script>
document.title = 'someTitleSetByAnyComponent'
</script>
```

As for SEO/social crawlers I'd recommend to disable streaming. This is actually what `react-streaming` does: https://github.com/brillout/react-streaming#options.

As for DX I'm thinking of that:

```js
import { useTitle } from 'vike-react/useTitle'
// Can be vike-react-query or vike-react-telefunc
import { useData } from 'vike-react-someDataFetchingLibrary'

function Product() {
  const data = useData(() => fetch('...'))
  const head = useHead()
  head.setTitle(data.product.name)
  // No effect if streaming (which is fine since streaming is disabled for SEO/social bots)
  head.setDescription(data.product.description)
}
```

@AndrejNemec Thoughts?

**Comment by AndrejNemec** [comment]
That's a great idea. I would definitely also create components that use the `useHead` hook, allowing the setting of the `title, description,` and other useful meta tags like `og:X, twitter:X `through components like `<HeadTitle/>`, `<HeadMeta/>`, `<HeadLink/>`, etc.

Furthermore, it would be beneficial to implement a robust injection system for packages that will be outside of the vike-react repository. Currently, it's not properly resolved and there are quite a few shortcomings. If I want to register a plugin to vike-react, it's quite a pain.

I propose something like this:

Let's say in the application I want to register the module: `@vike-react/head`

In the application, a config would be created: `+modules.ts`

```ts
export default {
  'vike-react-head': {
    server: 'import:@vike-react/head/module/server...',
    client: 'import:@vike-react/head/module/client...'
  },
  'vike-react-query': { /* ... */ },
  // ...etc
}
```

**Comment by brillout** [comment]
The plan so far is this: https://github.com/vikejs/vike/issues/1283. Which is actually needed for seamlessly integrating `vike-react-query` with `vike-react`. But, if you think it isn't enough, then elaborate on any concrete issue you're having.
