### ISSUE TITLE
Don't force user to use `pageContext.httpResponse.pipe()`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-react#38]
See https://github.com/vikejs/vike-react/pull/37#issuecomment-1833295416.

**Comment by phonzammi** [comment]
> I think the only solution is to have a new setting `stream: boolean`.

I thought exactly the same.

Here are some usecases I've been thinking for a while (cmiiw):

if `ssr: true` then `stream` can be false or true

if `ssr: false` then `stream` must false

1. set the `stream` setting manually:
   `ssr` is default to true, 
   `stream` default to false.
    If users want to use `httpResponse.pipe()`, then they have to set `stream: true`, otherwise trow an error to return 
   `res.status(statusCode).send(body)` or set `stream: true`.
    Pros : users have full control about streaming
    Cons (maybe) : users forced to set the `stream` setting

2. set `stream` setting automatically
If we can somehow find out what is returned from users server.js, (`httpResponse.pipe()` or `res.status(statusCode).send(body)`) then set `stream` to true or false automatically.
Pros: users don't need to think about `stream` setting
Cons: users don't have full control about streaming

And we also need to think about local config.h.ts, e.g /pages/posts/config.h.ts

Just to mention, right now if we don't set `ssr` to true or false in the `config.h.ts` then in `onRenderHtml()` `pageContext.config.ssr` is undefined

Any additional thought @AurelienLourot ?

**Comment by AurelienLourot** [comment]
Thanks a lot for looking into this @phonzammi 

I would be for this:
1. `ssr`, default is `true`
2. `stream`, default is `true`, value is ignored when `ssr` is `false`

The way we expect most people to use `vike-react` is by scaffolding a project with https://batijs.github.io/ .Bati will make sure to scaffold a server code that works together with the `vike-react` options it selects. What do you think?

**Comment by phonzammi** [comment]
Wow @AurelienLourot , that makes sense, I never thought that.

**Comment by phonzammi** [comment]
> Update: Just to mention, right now even if we set ssr to true or false in the config.h.ts, then in onRenderHtml() pageContext.config.ssr is undefined, is this intentional?

@brillout & @AurelienLourot, should we concern about this? We can fix it alongside fixing this current stream setting

**Comment by AurelienLourot** [comment]
> pageContext.config.ssr is undefined, is this intentional?

Yes, that's because that config is `config-only` (`env: {config: true}` used to be called `env: 'config-only'` in the past. I'd like to document `env` better in the future by the way, see #1300), i.e. that config exists in the "config" environment, but not in the server and client environments.

This is enough, we don't need to have this config also in client environment (and bloat it) as there we can just know if SSR is enabled or not by looking at whether `Page` is defined or not
