### ISSUE TITLE
Updating `lang` on client-side navigation

### ISSUE THREAD

**Issue by AurelienLourot** [vikejs/vike-react#59]
The user may change the `lang` setting per-page based on i18n. On client-side navigation, [onRenderClient](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/onRenderClient.tsx#L28) should adapt `lang` in the existing DOM.

CC @phonzammi

If no one objects, we should duplicate this issue to other [Vike extensions](https://vike.dev/vike-packages).

**Comment by brillout** [comment]
👍 Makes sense.

**Comment by phonzammi** [comment]
Yes, I think your idea is better.

FYI, my idea was to add an optional attribute to the `a href` link, like `reload?: boolean`.

```ts
<p>Choose Lang</p>
<a href="http://domain.com?lang=id" reload="true">Indonesia</a>
<a href="http://domain.com?lang=en" reload="true">English</a>
```

Then the link will behave like default (not intercepted by vike routing), navigation will be server routed
