### ISSUE TITLE
ssr:false doesn't work in latest version

### ISSUE THREAD

**Issue by trflagg** [vikejs/vike-react#65]
I'm trying to follow the [ssr-spa example](https://github.com/vikejs/vike-react/blob/main/examples/ssr-spa/pages/spa/%2Bconfig.h.ts) and set `ssr: false` in my +config.h  but it isn't having any effect.

After further research, I can see that work was done[ in a previous commit to support this](https://github.com/vikejs/vike-react/commit/e2729d3a25a1d456c651c44758b9deb449ae2e17#diff-543d3390daaa9c91b0973411ea9e9e65ba966a33d1d64f030c166a42d49a3fff), but the change doesn't exist in the latest version of [onRenderClient](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/onRenderClient.tsx) or [onRenderHTML](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/onRenderHtml.tsx).

Where did this work go?  

It looks like there was a reorganization at some point, but it's very confusing to have the config value appear in the examples and documentation but not supported in the actual repo (and also really confusing for the examples' [package.json](https://github.com/vikejs/vike-react/blob/vike-react%400.3.8/examples/ssr-spa/package.json) to link to `workspace:*`).

If we could get an update or maybe a new repo to point to or something that would be very helpful. Thanks in advance for you work and help on this.

For the time being, I'm going to try and recreate the onRenderClient and onRenderHTML from the version I found previously in the repo and see if that gets picked up and works.

**Comment by AurelienLourot** [comment]
> but it isn't having any effect.

Strange, the example is working fine for me. Can you please push your non-working code somewhere?


> but the change doesn't exist in the latest version of [onRenderClient](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/onRenderClient.tsx) or [onRenderHTML](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/onRenderHtml.tsx).

This is now implemented by using an [effect](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/%2Bconfig.ts#L62). Toggling `ssr` makes `Page` defined/undefined, and this is how `onRender{Client,Html}` knows whether there is SSR or not.

> and also really confusing for the examples' [package.json](https://github.com/vikejs/vike-react/blob/vike-react%400.3.8/examples/ssr-spa/package.json) to link to `workspace:*`

Yes the examples use `workspace:` in order to use the not-yet-published version in `main`. You can replace that with the actual version of `vike-react` in your project. If you are scaffolding a new project, you can use https://batijs.github.io/, which will do this for you.

**Comment by trflagg** [comment]
> This is now implemented by using an [effect](https://github.com/vikejs/vike-react/blob/main/packages/vike-react/renderer/%2Bconfig.ts#L62). Toggling ssr makes Page defined/undefined, and this is how onRender{Client,Html} knows whether there is SSR or not

Ahhh, I see!  

I wonder if I still had something running somewhere that was evaluating the `Page` anyways. I'm trying to test an sdk that's only linked to via a `<script>` tag in the header but even with `ssr: false` the page was failing on the server so I knew it was still getting evaluated somewhere. But maybe I had something still lying around in the process somewhere from before I integrated your plugin.

I'm converting a site made with an older version of Vike so that's why I was unable to scaffold with Bati.

I have my own solution now based on that older code I found that's a little more customized for my needs, but maybe I'll go back and see if I can get the plugin to work again. 

Either way, you can consider this issue closed.

Thanks!

**Comment by AurelienLourot** [comment]
Great, I'm glad things are working for you now :) By the way if your company is up for it, [sponsoring](https://github.com/sponsors/vikejs/) would help us a lot
