### ISSUE TITLE
Provide an export PageContextProvider

### ISSUE THREAD

**Issue by ivangreene** [vikejs/vike-react#71]
Some users may have needs that dictate they use something other than the provided onRenderClient/onRenderHtml in this package; so an export of PageContextProvider would be nice so that it can be set up to use the `useData`/`usePageContext` hooks

**Comment by brillout** [comment]
Why do you want to use your on onRender{Client,Html}?

So far I'm thinking it should be all-or-nothing.

**Comment by ivangreene** [comment]
@brillout thanks for a quick response. I will take a closer look at the provided onRender classes, they may suit my needs. I am doing some custom stuff in my onRenderHtml, but I can probably move it to the Page instead

**Comment by brillout** [comment]
Closing, but let me know if you still need something.
