### ISSUE TITLE
vike-react-query questions

### ISSUE THREAD

**Issue by kevincrossgrove** [vikejs/vike-react#92]
1. Is there any recommended approach for setting the page title dynamically when using `vike-react-query`?  I am using `useSuspenseQuery` with `telefunc`, and want to avoid fetching the same data twice, one time just for setting the page title

2. Is there a way to prevent a `useSuspenseQuery` from refetching (on the server) when the client already has the data for the specific cache key from another page?

**Comment by brillout** [comment]
1. The plan is to use React's 19 built-int `<title>` support, see https://github.com/vikejs/vike-react/issues/88. You can also try to implement a solution on user land but note that it isn't trivial, see https://github.com/vikejs/vike-react/issues/67 and https://github.com/vikejs/vike-react/issues/36#issuecomment-1842870621.
2. I think @nitedani (author of `vike-react-query`) will probably know more about this.

Closing but let's continue the discussion.

**Comment by nitedani** [comment]
> 1\. Is there any recommended approach for setting the page title dynamically when using `vike-react-query`?  I am using `useSuspenseQuery` with `telefunc`, and want to avoid fetching the same data twice, one time just for setting the page title

`useSuspenseQuery` deduplicates and caches queries. If you have it at two different places with the same `queryKey`, it will only do one request.



> 2\. Is there a way to prevent a `useSuspenseQuery` from refetching (on the server) when the client already has the data for the specific cache key from another page?

You can set `refetchOnMount: false` - https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

**Comment by brillout** [comment]
@kevincrossgrove We're adding further documentation at https://github.com/vikejs/vike-react/pull/97. Let us know if you still have questions.

**Comment by kevincrossgrove** [comment]
> @kevincrossgrove
> 
> > 1. Is there any recommended approach for setting the page title dynamically when using `vike-react-query`?  I am using `useSuspenseQuery` with `telefunc`, and want to avoid fetching the same data twice, one time just for setting the page title
> 
> `useSuspenseQuery` deduplicates and caches queries. If you have it at two different places with the same `queryKey`, it will only do one request.
> 
> > 2. Is there a way to prevent a `useSuspenseQuery` from refetching (on the server) when the client already has the data for the specific cache key from another page?
> 
> You can set `refetchOnMount: false` - https://tanstack.com/query/latest/docs/framework/react/reference/useQuery Or you can set a higher `staleTime` on the query: `staleTime: 60000` (one minute)
> 
> You can also set the `QueryClient` defaults inside a Vike config file:
> 
> ```ts
> // +config.ts
> 
> export default {
>   ...
>   queryClientConfig: {
>     defaultOptions: {
>       queries: {
>         staleTime: 60000,
>       },
>     },
>   },
> };
> ```

@nitedani Thank you very much. Both are excellent solutions
